---
# Source: b4b-paytas-pa-liquibase/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: paytas-pa-service-b4b-paytas-pa-liquibase
  namespace: int-b4b-pa
  labels:
    helm.sh/chart: b4b-paytas-pa-liquibase-0.0.1
    app.kubernetes.io/name: paytas-pa-service
    app.kubernetes.io/instance: b4b-paytas-pa-liquibase
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: paytas-pa-service
      app.kubernetes.io/instance: b4b-paytas-pa-liquibase
  template:
    metadata:
      labels:
        app.kubernetes.io/name: paytas-pa-service
        app.kubernetes.io/instance: b4b-paytas-pa-liquibase
        app.kubernetes.io/version: "0.0.1"
        job-name: paytas-pa-service-b4b-paytas-pa-liquibase
    spec:
      automountServiceAccountToken: false
      serviceAccountName: default
      imagePullSecrets:
        - name: gitlab-5005
      containers:
        - name: b4b-paytas-pa-liquibase
          image: "gitlab.int.master.lan:5005/delivery/b4b/b4b-delivery-paytas-pa-service/b4b-paytas-pa-liquibase/b4b-paytas-pa-liquibase:0.0.1"
          imagePullPolicy: Always
          resources:
            null
          volumeMounts:
          env:
            #secretProvider.envSecrets
            - name: PAYTAS_DB_OWNER
              valueFrom:
                secretKeyRef:
                  name: paytas-pa-service-b4b-paytas-pa-liquibase
                  key: PAYTAS_DB_OWNER
            - name: PAYTAS_DB_OWNER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: paytas-pa-service-b4b-paytas-pa-liquibase
                  key: PAYTAS_DB_OWNER_PASSWORD
            #envConfig
            - name: DB_TYPE
              valueFrom:
                configMapKeyRef:
                  name: paytas-pa-service-b4b-paytas-pa-liquibase
                  key: DB_TYPE
            - name: DB_VERSION
              valueFrom:
                configMapKeyRef:
                  name: paytas-pa-service-b4b-paytas-pa-liquibase
                  key: DB_VERSION
            - name: LIQUI_CONTEXT
              valueFrom:
                configMapKeyRef:
                  name: paytas-pa-service-b4b-paytas-pa-liquibase
                  key: LIQUI_CONTEXT
            - name: PAYTAS_DB_CONNECTION_URL
              valueFrom:
                configMapKeyRef:
                  name: paytas-pa-service-b4b-paytas-pa-liquibase
                  key: PAYTAS_DB_CONNECTION_URL
            - name: PAYTAS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: paytas-pa-service-b4b-paytas-pa-liquibase
                  key: PAYTAS_DB_NAME
            - name: PAYTAS_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: paytas-pa-service-b4b-paytas-pa-liquibase
                  key: PAYTAS_DB_USERNAME
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: paytas-pa-service-b4b-paytas-pa-liquibase
                  key: TZ
            #envFieldRef
      volumes:
      restartPolicy: Never
      terminationGracePeriodSeconds:
