---
# Source: b4b-paytas-pa-liquibase/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
      - name: helloworld
        image: "hello-world:latest"
        env:
          - name: testsecret
            valueFrom:
              secretKeyRef:
                name: paytas-pa-service-b4b-paytas-pa-liquibase
                key: PAYTAS_DB_OWNER
      restartPolicy: Never
  backoffLimit: 4
