---
# Source: b4b-paytas-pa-liquibase/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: paytas-pa-service-b4b-paytas-pa-liquibase
  namespace: default
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    helm.sh/chart: b4b-paytas-pa-liquibase-0.0.1
    app.kubernetes.io/name: paytas-pa-service
    app.kubernetes.io/instance: b4b-paytas-pa-liquibase
    app.kubernetes.io/version: "0.0.1"
    app.kubernetes.io/managed-by: Helm
type: Opaque
data:
  PAYTAS_DB_OWNER : aW50X2I0Yl9wYV9vd25lcg==
  PAYTAS_DB_OWNER_PASSWORD : aW50X2I0Yl9wYV9vd25lcg==
